export const getCourseListInfo = state => state.courseList;
export const getCourseDetailInfo = state => state.courseDetail;
export const getCourseOpenInfo = state => state.openInfo;
export const getLessonEnroll = state => state.enroll;
export const getOrderConfirm = state => state.order;
export const getCourseScrollTop = state => state.courseScrollTop;
export const getEvaluateList = state => state.evaluateList;
export const getCanWXShare = state => state.canWXShare;
export const getShowBottom = state => state.showBottom;
