export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const CHANGE_IS_NOTICE = 'CHANGE_IS_NOTICE';
export const CHANGE_CALENDAR = 'CHANGE_CALENDAR';
