export const FETCH_ENROLL_LIST = 'FETCH_ENROLL_LIST'
export const FETCH_MONEY_BALANCE = 'FETCH_MONEY_BALANCE'
export const FETCH_MONEY_BILL = 'FETCH_MONEY_BILL'
export const FETCH_MONEY_DEBIT = 'FETCH_MONEY_DEBIT'
