<?php


namespace _;


use Core\library\Tool;
use Core\unitAPI;
use Core\unitDoAction;

class ctrlAb extends ctrl_
{
    use unitAPI;
    use unitDoAction;

    private $platform = '-';

    public function runBefore()
    {
        $ip = \input::ip();
        $allowed = config::load('option', 'allowed', 'internal.IPs', []);
        return Tool::IPcheck($ip, $allowed);
//        return parent::runBefore(); // TODO: Change the autogenerated stub
    }

    public function _DO_user()
    {
        $usn = $this->apiGET('usn');
        $res = servCache::sole($this->platform)->usn2base($usn);
        $res['avatar'] = \view::upload("user/$usn/avatar-avatar", Tool::timeEncode($res['tms_update']));
        $this->apiSuccess($res);
    }

    public function _DO_slice($type)
    {
        $lessonSn = $this->apiGET('lesson_sn');
        $cursor = $this->apiGET('cursor', '-');
        $toward = $this->apiGET('toward', data::TOWARD_NEXT);
        $limit = $this->apiGET('limit', 10);
        $usn = $this->apiGET('usn');
        $srvCache = servCache::sole($this->platform);
        $caKey = servCache::TAG_LESSON_AUTH."$lessonSn|$usn";
        $caRes = $srvCache->get($caKey);
        $servLesson = servLesson::sole($this->platform);
        if ($caRes === false) {
            $caRes = $servLesson->checkAccess($lessonSn, $usn) ? 'yes' : 'no';
            $srvCache->set($caKey, $caRes, SECONDS_MINUTE);
        }
        if ($caRes != 'yes') {
            $this->apiFailure(['-1', 'no access']);
        }
        $ckey = servCache::TAG_LESSON_SLICE."$type|$lessonSn|$cursor|$toward|$limit";
        if (($data = $srvCache->getJson($ckey)) !== null) {
            $this->apiSuccess($data);
        }
        switch ($type) {
            case 'tim':
                $data = $servLesson->sliceRecord(dataLessonRecord::FORM_TIM, $lessonSn, $cursor, $toward, $limit);
                break;
            default:
                $data = [];
        }
        $srvCache->setJson($ckey, $data, (count($data)==$limit) ? SECONDS_MINUTE : 5);
        $this->apiSuccess($data);
    }

}