export const FETCH_COURSE_LIST = 'FETCH_COURSE_LIST';
export const FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL';
export const FETCH_OPEN_INFO = 'FETCH_OPEN_INFO';
export const FETCH_EVALUATE_LIST = 'FETCH_EVALUATE_LIST';
export const FETCH_COURSE_EDIT = 'FETCH_COURSE_EDIT';
